"""

A code made to simulate the game from the Numberphile video:
YouTube: Derangements - Numberphile
https://www.youtube.com/watch?v=pbXg5EI5t4c

Author: Carlos Jose Vargas Aguero
email: carlos.vargasaguero@gmail.com

This part of the program is to plot the ratio wins generated by the fortran code
"""

import numpy as np
import matplotlib.pyplot as plt

#Loading the data
x,y = np.loadtxt("score_ratio.txt",unpack=True)

#Plotting the data
fig, ax = plt.subplots()
ax.plot(x,y,'ro',markersize=7)
ax.set_xscale('log')
ax.set_xlabel('Number of cards')
ax.set_ylabel('Ratio of wins')
ax.set_ylim([0,1])
ax.set_title('Numberphile Derangement')
fig.savefig('numberphile_nerangement.svg')
